### ISSUE TITLE
joinImages is not a function

### ISSUE THREAD

**Issue by 1011382654** [ccpu/join-images#12]
framework: Nuxt 3
file: server/api/image.ts

import joinImages from 'join-images';
export default defineEventHandler(async (event) => {
    joinImages(['image-1.png', 'image-2.png']).then((img) => {
        // Save image as file
        img.toFile('out.png');
      });
    return image
})

### error:

`[nuxt] [request error] joinImages is not a function
  at /F:/wordpress/nuxt3/nuxt-app/.nuxt/dev/index.mjs:409:3
  at async /F:/wordpress/nuxt3/nuxt-app/node_modules/h3/dist/index.mjs:417:19
  at async Server.nodeHandler (/F:/wordpress/nuxt3/nuxt-app/node_modules/h3/dist/index.mjs:367:7)`

**Comment by erickythierry** [comment]
> framework: Nuxt 3 file: server/api/image.ts
> 
> import joinImages from 'join-images'; export default defineEventHandler(async (event) => { joinImages(['image-1.png', 'image-2.png']).then((img) => { // Save image as file img.toFile('out.png'); }); return image })
> 
> ### error:
> `[nuxt] [request error] joinImages is not a function at /F:/wordpress/nuxt3/nuxt-app/.nuxt/dev/index.mjs:409:3 at async /F:/wordpress/nuxt3/nuxt-app/node_modules/h3/dist/index.mjs:417:19 at async Server.nodeHandler (/F:/wordpress/nuxt3/nuxt-app/node_modules/h3/dist/index.mjs:367:7)`

I had this same problem.
I managed to solve it by changing the import:
`import * as ji from 'join-images';`

and then using the function:

`ji.joinImages(...)`

I hope it helps you

**Comment by 1011382654** [comment]
> > framework: Nuxt 3 file: server/api/image.ts
> > import joinImages from 'join-images'; export default defineEventHandler(async (event) => { joinImages(['image-1.png', 'image-2.png']).then((img) => { // Save image as file img.toFile('out.png'); }); return image })
> > ### error:
> > `[nuxt] [request error] joinImages is not a function at /F:/wordpress/nuxt3/nuxt-app/.nuxt/dev/index.mjs:409:3 at async /F:/wordpress/nuxt3/nuxt-app/node_modules/h3/dist/index.mjs:417:19 at async Server.nodeHandler (/F:/wordpress/nuxt3/nuxt-app/node_modules/h3/dist/index.mjs:367:7)`
> 
> I had this same problem. I managed to solve it by changing the import: `import * as ji from 'join-images';`
> 
> and then using the function:
> 
> `ji.joinImages(...)`
> 
> I hope it helps you

thank you! Your reply solved my problem
