### ISSUE TITLE
Missing "tslib"

### ISSUE THREAD

**Issue by vsjov** [ccpu/join-images#7]
You are missing "tslib" in your package.json file.

When I try to use it in a project that doesn't use typescript, it outputs this error message:

```bash
λ node test.js
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- [my path]\node_modules\join-images\lib\main.js
```

I have resolved it by including 'tslib' in my own `package.json`, but the real solution would be to include it here.

**Comment by ccpu** [comment]
Thanks for the suggestion, I have added `tslib` to dependencies.
