### ISSUE TITLE
Must define offsetX for ImageSrcs if offsetY is defined, otherwise NaN calculation.

### ISSUE THREAD

**Issue by JoseHdez2** [ccpu/join-images#8]
At the moment, any user must define an `offsetX` for the ImageSrcs if `offsetY` is defined, otherwise the width is calculated as `NaN` internally and an error is shown (`Error: Expected valid width, height and channels to create a new input image`).

The expected behavior should be that `offsetX` will be set to `0` implicitly instead of having to define it explicitly.

Example working code, comment explains what breaks:
```typescript
async function stitchImagesInMemory(images: Buffer[], yOffsets: number[]): Promise<Sharp> {
    // will error out if no offsetX is explicitly defined in the next line.
    const images2: ImageSrc[] = images.map((img, i) => { return {src: img, offsetY: yOffsets[i], offsetX: 0} }); 
    const resultImg = await joinImages(images2);
    return resultImg;
}
```

**Comment by ccpu** [comment]
Thank you for pointing this out, I have applied the fix.

**Comment by JoseHdez2** [comment]
That was fast! Thank you!
